### ISSUE TITLE
Help to run athena-voice-client Fedora Linux

### ISSUE THREAD

**Issue by kuboosoft** [athena-voice/athena-voice-client#15]
Hi. I am trying to create an RPM for Fedora Linux. I builded a rpm for all dependencies for athena-voice-client, but I don't found a python module. Can you help? Who provides "client"? thanks.

Log: 

[makerpm@localhost client]$ python3 brain.py
Traceback (most recent call last):
  File "brain.py", line 12, in <module>
    import client.stt as stt
ImportError: No module named 'client'

**Comment by rcbyron** [comment]
Hi there! This error is because the project/client directory needs to be in your operating system's PYTHONPATH environment variable. I'm currently looking into ways to automatically add my "client" module to the PYTHONPATH. If you have bash, try this command "export PYTHONPATH=${PYTHONPATH}:/<path_to_project_directory>" (taken from here: https://users-cs.au.dk/chili/PBI/pythonpath.html)

Let me know how that goes!

Thanks,
Connor

**Comment by rcbyron** [comment]
After manually installing PyAudio, you can now use "pip install AthenaVoice". This should fix the PYTHONPATH issue since athena will install to site-packages (already in the default PYTHONPATH).

**Comment by kuboosoft** [comment]
Thanks I will try again.
